[package]
name = "echarts-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.191.0"
handlebars = "4.3.7"
serde_json = "1.0.99"
serde_v8 = "0.102.0"
