[package]
name = "echarts-gallery"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.0"
axum = "0.6.18"
chrono = "0.4.26"
lazy_static = "1.4.0"
rand = "0.8.5"
tokio = "1.29.1"
echarts = { path = "../echarts" }
serde_json = "1.0.99"
serde = "1.0.164"
