[package]
name = "charming"
description = "A visualization library for Rust"
version = "0.1.2"
edition = "2021"
authors = ["Yuankun Zhang <i@yuankun.me>"]
homepage = "https://github.com/yuankunzhang/echarts-rs"
documentation = "https://github.com/yuankunzhang/echarts-rs"
keywords = ["rust", "echarts", "visualization", "chart"]
categories = ["data-visualization", "graphics"]
license = "MIT/Apache-2.0"
readme = "../README.md"

[dependencies]
deno_core = { version = "0.195.0", optional = true }
gdk-pixbuf = { version = "0.17.10", optional = true }
handlebars = "4.3.7"
serde = { version = "1.0.164", features = ["derive"] }
serde-wasm-bindgen = {version = "0.5.0", optional = true }
serde_json = "1.0.99"
serde_v8 = { version = "0.106.0", optional = true }
wasm-bindgen = { version = "0.2.87", optional = true }

[dependencies.web-sys]
version = "0.3.64"
optional = true
features = [
    "Window",
    "Document",
    "Element",
]

[features]
ssr = ["deno_core", "gdk-pixbuf", "serde_v8"]
wasm = ["serde-wasm-bindgen", "wasm-bindgen", "web-sys"]
